version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.12
    container_name: mosquitto
    ports:
      - 8883:8883
      - 9001:9001
    volumes:
      - $PWD/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - $PWD/config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    networks:
      - mosquitto

  telegraf:
    image: telegraf:1.19.3
    container_name: telegraf
    env_file:
      - config.env
    networks:
      - mosquitto
      - influxdb
    volumes:
      - $PWD/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influxdb:
    image: influxdb:2.0.8
    container_name: influxdb
    ports:
      - 8086:8086
    env_file:
      - config.env
    networks:
      - influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:8.1.4
    container_name: grafana
    env_file:
      - config.env
    ports:
      - 3000:3000
    networks:
      - influxdb
    volumes:
      - $PWD/config/grafana_influxdb_datasource.yml:/etc/grafana/provisioning/datasources/influxdb.yml:ro

networks:
  mosquitto:
  influxdb:

volumes:
  influxdb-data:
